xception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MG\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__
.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:\Users\MG\OneDrive\Desktop\PROJECT\TRACKING\main\modules\gui.py", line
 703, in _on_roi_click
    canvas_width = self.roi_canvas.winfo_width()
                   ^^^^^^^^^^^^^^^
AttributeError: 'SpeedEstimatorGUI' object has no attribute 'roi_canvas'


draw roi